version: '3.8'

services:
  postgres:
    container_name: pg_ddd_user
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: user_db
